language: java
sudo: false
script: mvn test jacoco:report coveralls:report
jdk:
- oraclejdk7
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: GFXQCHX4NMLECxsP5kuA3iizXgJRkvVNbhB8FQosVpw+dtrVSrgh77AtZPW6xNeTYqe7gZZCqSGX2QSkCiIxPDIZeoGZEdxyIsHM8FJkJzfX754jfqIqPGslm9RnKWTPCxUcTQuVjt2f9Csx3wnfaJH9RKmck0/pPvNZXduCPVDyzGVvwMkMUQm7vtlu8UttHfuBIZb/wgaKCLpDoMm5IJil7U5v3qajx6iJq5M6I0M02cD2/zc+Nup9Jww08SvVahFm7qwOy1PwOLtv8+UOnjGy0PcCpcCNcBY0TRFuM2mOwDVvMDRjsOhfiVheA2Er11lKV4B44afuRu7mNwUvJSy0wQoLqbQgRQctkZWbzZK2+lJ30LAqC5wFd9lNoP/UW4LbDiwwQ6JfZ7bl3nln2QH1hnPRV1zi9hCYR/LfKY/79/YV9hCHVgDEvFZi2Sbs3Yf2CFAPArUggE/jfqX1yRljfoJQgGkBBqnv6xFFXQcMllkUAMeNoN4lyAQplF69tFU5ZrzFRZ9pOEpBLueIzCDjuyXf3xGKDCZNril1iRiQRnXUZ5pLwlw++N1jL9lvDGC8IofgbO7waIGlCGyV8zpeK53pxDeARlbRQeJylsi965BjSPK7krmN5L5/hKizNVV6M5ltX/ETqMPYu6p189vPsieevEcUHeS0D18TJ/g=
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { mvn deploy --settings .travis-settings.xml
  -DskipTests=true -B; };'
